name: Build and Test Linux Source Tree

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    uses: alok0366/actions-test/.github/workflows/main.yml@main
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
